### ISSUE TITLE
cdTool and Monterey

### ISSUE THREAD

**Issue by grylem** [Emrys365/alfred_workflows#2]
Hi
please update cdTool for latest Monterey.
Thanks.

**Comment by Emrys365** [comment]
Hi @grylem, could you paste your error message here for me to locate the problem? I am now using Monterey 12.3 and I didn't have any problem with this workflow.

You could grab the error message by opening the workflow page in Alfred and then clicking on the "Bug" button on the upper right corner.
A panel will show in the bottom. Then run the workflow as usual, and the log message will be displayed in the panel.

![debug](https://user-images.githubusercontent.com/18532145/160067063-73c683db-01dc-4128-8961-a5cbe20b24cd.png)

**Comment by ytarakji** [comment]
Hi, I'm having a little issue on Monterey 
since the last update, apple removed python 2.x from Monterey, and the workflow broke showing this message 3
![image](https://user-images.githubusercontent.com/31030392/160762756-a32380fb-3f1a-4cf9-a356-6dbab5f9c845.png)
as I didn't want to reinstall python 2.x what I did was just made a link to python3 as python
like so 
`ln -s /opt/homebrew/bin/python3 /opt/homebrew/bin/python`
and now `python` points to python3 
then the workflow works! but not everything
I mainly use frac, and sqrt 
sqrt works as expected but frac is throwing this error 
![image](https://user-images.githubusercontent.com/31030392/160763106-1efa425d-640e-4806-9dc7-bdc9ba8797f0.png)
I'm trying to debug it, but I'm not having much luck, I assume the workflow was written with python 2.x in mind 

Edit: Yeah can confirm most of the functions aren't working except [sqrt, num, bit] although [num, bit] are throwing a warning
![image](https://user-images.githubusercontent.com/31030392/160764142-6a6a74f6-8b1e-46ff-b397-4a4732b862e6.png)

**Comment by yamyoume** [comment]
> 

Wait You're on 12.3??
did you reinstall python2?

**Comment by ytarakji** [comment]
> Hi @grylem, could you paste your error message here for me to locate the problem? I am now using Monterey 12.3 and I didn't have any problem with this workflow.
> 
> You could grab the error message by opening the workflow page in Alfred and then clicking on the "Bug" button on the upper right corner. A panel will show in the bottom. Then run the workflow as usual, and the log message will be displayed in the panel.
> 
> ![debug](https://user-images.githubusercontent.com/18532145/160067063-73c683db-01dc-4128-8961-a5cbe20b24cd.png)

Wait You're on 12.3??
did you reinstall python2?

**Comment by Emrys365** [comment]
> Wait You're on 12.3?? did you reinstall python2?

Oh yes, I have my own Python 2 installed in `/usr/local/bin/`, and that was used as the language interpreter by default. I guess that's why I didn't observe any error.

@grylem @yamyoume I just updated all workflows. Could you test whether they are working now?
> Note that you might need to install Python3 or Python2 to `/usr/local/bin/`, because I assume the binary file `/usr/local/bin/python` exists when updating the workflows.
> Both Python2 and Python3 should be supported now.

**Comment by ytarakji** [comment]
Hello @Emrys365 Thank you for updating the workflow, 
I can confirm everything works except [gcd, lcm] on my end where I have only python 3 installed
![image](https://user-images.githubusercontent.com/31030392/160938090-eb44c885-9d35-4369-b7ee-8bf615f144fd.png)

![image](https://user-images.githubusercontent.com/31030392/160938158-38dd41ce-daeb-4536-82e9-6d29f9dd4172.png)

**Comment by ytarakji** [comment]
Oh and btw my workflow just picked up the path for the python binary on it's own from `/opt/homebrew/bin`

![image](https://user-images.githubusercontent.com/31030392/160939137-8edfb650-8203-442b-bed7-ff9ddbce496f.png)

**Comment by Emrys365** [comment]
> Hello @Emrys365 Thank you for updating the workflow, I can confirm everything works except [gcd, lcm] on my end where I have only python 3 installed!

@yamyoume  Ah I didn't notice that `gcd` has been deprecated as of Python 3.9, because I used Python 3.7 locally.
I just updated MathTools again and slightly change its output format for floating/fraction numbers. Is it working now?

**Comment by ytarakji** [comment]
> 

Yes Sir!, it's all working now
